import { useMemo, useState } from 'react';
import { ArrowLeft, ArrowRight, Check, Eye, Flag, Heart, MessageSquareWarning, RotateCcw, Settings2, Sparkles, X } from 'lucide-react';
import { emotionalState, experienceScenes, type Choice } from '../data/sensitivityExperience';
import experienceCover from '../assets/images/experience_cover.png';
import experienceSceneVideo from '../assets/images/experience_scene_video.png';
import experienceSceneChat from '../assets/images/experience_scene_chat.png';
import experienceSceneViral from '../assets/images/experience_scene_viral.png';
import experienceSceneAlgorithm from '../assets/images/experience_scene_algorithm.png';
import experienceSceneSaturation from '../assets/images/experience_scene_saturation.png';
import experienceClosing from '../assets/images/experience_closing.png';

type View = 'cover' | 'instructions' | 'scene' | 'feedback' | 'result' | 'tips' | 'closing';
const faces = ['☺', '🙂', '😐', '☹', '☹'];
const labels = ['Estado narrativo: apertura', 'Estado narrativo: atención', 'Estado narrativo: pausa', 'Estado narrativo: inquietud', 'Estado narrativo: alerta'];
const sceneMedia = [
  { src: experienceSceneVideo, alt: 'Teléfono mostrando un video desenfocado en una red social.' },
  { src: experienceSceneChat, alt: 'Fruta y cuchillo como imagen simbólica de contenido sensible.' },
  { src: experienceSceneViral, alt: 'Granada deteriorada como representación abstracta de una publicación viral.' },
  { src: experienceSceneAlgorithm, alt: 'Televisor ilustrado como símbolo de recomendaciones invasivas.' },
  { src: experienceSceneSaturation, alt: 'Persona agotada frente a un portátil.' }
];

export function SensitivityExperience({ onClose }: { onClose: () => void }) {
  const [view, setView] = useState<View>('cover'); const [index, setIndex] = useState(0); const [answers, setAnswers] = useState<Choice[]>([]); const [choice, setChoice] = useState<Choice | null>(null);
  const score = useMemo(() => answers.reduce((sum, item) => sum + item.score, 0), [answers]);
  const state = emotionalState(score + (choice?.score ?? 0)); const scene = experienceScenes[index];
  const reset = () => { setView('cover'); setIndex(0); setAnswers([]); setChoice(null); };
  const confirm = () => { if (!choice) return; setAnswers(prev => [...prev, choice]); setView('feedback'); };
  const next = () => { if (index === experienceScenes.length - 1) { setChoice(null); setView('result'); } else { setIndex(i => i + 1); setChoice(null); setView('scene'); } };
  const sensitive = score >= 3;
  return <section className="sensitivity-experience fixed inset-0 z-[100] overflow-y-auto bg-[#090a0b] text-[#f2f2f2]" aria-label="Experiencia interactiva ¿Cuánto te afecta?">
    <div className="pointer-events-none fixed inset-0 grain-overlay opacity-40" />
    <header className="sticky top-0 z-10 flex h-16 items-center justify-between border-b border-white/10 bg-[#090a0b]/90 px-5 backdrop-blur md:px-10"><button onClick={onClose} className="xp-link"><ArrowLeft size={17}/> Volver al blog</button><span className="xp-wordmark">¿CUÁNTO <i>TE AFECTA?</i></span><button onClick={onClose} aria-label="Cerrar experiencia" className="xp-icon"><X /></button></header>
    <main className="relative mx-auto flex min-h-[calc(100vh-4rem)] max-w-6xl items-center px-5 py-10 md:px-10">
      {view === 'cover' && <div className="xp-cover"><div><p className="xp-kicker">EXPERIENCIA INTERACTIVA · 05 RELATOS</p><h1>¿CUÁNTO<br/><em>TE AFECTA?</em></h1><p>Un recorrido sobre cómo el consumo de contenido violento en internet puede influir en nuestra forma de sentir, interpretar y responder ante el sufrimiento de otras personas.</p><button className="xp-primary" onClick={() => setView('instructions')}>Comenzar <ArrowRight size={17}/></button></div><div className="xp-visual"><img src={experienceCover} alt="Persona observando contenido digital y conexiones de perfiles."/><span>CONTENIDO SENSIBLE<br/>SIN IMÁGENES EXPLÍCITAS</span></div></div>}
      {view === 'instructions' && <div className="xp-panel xp-center"><p className="xp-kicker">ANTES DE EMPEZAR</p><h2>¿CÓMO FUNCIONA?</h2><div className="xp-steps"><div><Eye/><b>1. Lee cada situación</b><span>Basada en situaciones habituales de internet.</span></div><div><MessageSquareWarning/><b>2. Toma una decisión</b><span>Elige cómo actuarías en cada caso.</span></div><div><ArrowRight/><b>3. Observa el recorrido</b><span>La escala es una mecánica narrativa, no una medición clínica.</span></div></div><EmotionBar state={0}/><button className="xp-primary" onClick={() => setView('scene')}>Entendido, empezar <ArrowRight size={17}/></button></div>}
      {(view === 'scene' || view === 'feedback') && <div className="xp-flow"><Progress index={index}/><div className="xp-story"><div className="xp-scene-media"><img src={sceneMedia[index].src} alt={sceneMedia[index].alt}/></div><div className="xp-story-symbol">{index === 0 ? <Flag/> : index === 1 ? <MessageSquareWarning/> : index === 2 ? <Heart/> : index === 3 ? <Settings2/> : <Sparkles/>}</div><p className="xp-kicker">ESCENA {index + 1} · {scene.label}</p><h2>{scene.title}</h2><p>{scene.story}</p></div><div className="xp-choice-area">{view === 'scene' ? <><h3>¿Qué harías?</h3><div className="xp-choices">{scene.choices.map(item => <button key={item.id} className={choice?.id === item.id ? 'selected' : ''} onClick={() => setChoice(item)} aria-pressed={choice?.id === item.id}><b>{item.id.toUpperCase()}.</b> {item.text}{choice?.id === item.id && <Check size={18}/>}</button>)}</div><button className="xp-primary self-end" disabled={!choice} onClick={confirm}>Ver reflexión <ArrowRight size={17}/></button></> : <div className="xp-feedback"><EmotionBar state={state}/><p className="xp-kicker">TU DECISIÓN: {choice?.id.toUpperCase()}</p><h2>{choice?.feedback}</h2><blockquote>{choice?.reflection}</blockquote><button className="xp-primary" onClick={next}>{index === 4 ? 'Ver resultado' : 'Continuar'} <ArrowRight size={17}/></button></div>}</div></div>}
      {view === 'result' && <div className="xp-panel xp-center"><EmotionBar state={emotionalState(score)}/><p className="xp-kicker">RECORRIDO COMPLETADO</p><h2>{sensitive ? 'TU FORMA DE ACTUAR IMPORTA' : '¿QUÉ ESTÁ CAMBIANDO?'}</h2><p className="xp-result-copy">{sensitive ? 'Tus decisiones reflejan una mayor disposición a cuestionar la difusión de contenido violento, considerar a las personas afectadas y actuar responsablemente en internet.' : 'Tus decisiones muestran una tendencia a interactuar con el contenido sin detenerte demasiado en sus posibles consecuencias. La exposición repetida puede influir en cómo interpretamos el sufrimiento, aunque sus efectos varían entre personas y situaciones.'}</p><p className="xp-disclaimer">Este recorrido no mide empatía ni realiza diagnósticos. Es una invitación a pensar en nuestras prácticas digitales.</p><div className="xp-actions"><button className="xp-secondary" onClick={reset}><RotateCcw size={16}/> Volver a intentar</button><button className="xp-primary" onClick={() => setView('tips')}>{sensitive ? 'Ver consejos' : 'Más información'} <ArrowRight size={17}/></button></div></div>}
      {view === 'tips' && <Tips onContinue={() => setView('closing')} />}
      {view === 'closing' && <div className="xp-panel xp-closing"><div className="xp-closing-media"><img src={experienceClosing} alt="Libro abierto y taza de café para el cierre reflexivo."/></div><p className="xp-kicker">FIN DEL RECORRIDO</p><h2>GRACIAS<br/>POR PARTICIPAR</h2><p>La forma en que consumimos internet también influye en el mundo que construimos. Mantener una mirada crítica y reconocer el sufrimiento ajeno es parte del cambio.</p><div className="xp-actions"><button className="xp-secondary" onClick={reset}><RotateCcw size={16}/> Repetir experiencia</button><button className="xp-primary" onClick={onClose}>Regresar al blog <ArrowRight size={17}/></button></div></div>}
    </main>
  </section>;
}
function EmotionBar({ state }: { state: number }) { return <div className="xp-emotions" role="img" aria-label={labels[state]}>{faces.map((face, i) => <span className={i === state ? `active face-${i}` : ''} key={i}>{face}</span>)}</div>; }
function Progress({ index }: { index: number }) { return <div className="xp-progress" aria-label={`Escena ${index + 1} de 5`}>{experienceScenes.map((_, i) => <span key={i} className={i <= index ? 'done' : ''}>{i + 1}</span>)}</div>; }
function Tips({ onContinue }: { onContinue: () => void }) { const tips = [['Cuestiona lo que consumes.', 'Pregúntate por qué estás viendo el contenido y qué aporta.'], ['Evita amplificar el daño.', 'No compartas imágenes violentas innecesariamente.'], ['Configura tus redes.', 'Usa preferencias, silenciamiento y reporte.'], ['Busca contexto.', 'Contrasta la información antes de difundirla.'], ['Reconoce a las personas.', 'Considera su dignidad, privacidad y consecuencias.'], ['Cuida tu bienestar digital.', 'Establece límites y busca apoyo si lo necesitas.']]; return <div className="xp-panel xp-tips"><p className="xp-kicker">RECURSOS PRÁCTICOS</p><h2>¿CÓMO MANTENER TU SENSIBILIZACIÓN EN INTERNET?</h2><div>{tips.map(([title, copy], i) => <article key={title}><span>0{i + 1}</span><h3>{title}</h3><p>{copy}</p></article>)}</div><button className="xp-primary" onClick={onContinue}>Finalizar <ArrowRight size={17}/></button></div>; }
